name: Trenitalia Hourly Watcher

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run-watcher:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run Watcher Script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }} # fix key below in final or keep standard
        run: |
          python watcher.py
